data:
  path: datasets/
  rebuild: False
  origin: csv
  indiv_split: 0.7
  date_split: 0.7
  indiv:

model:
  name: patch_tst
  modelpath: outputs/benchmark/patch_tst_revin/model.pt
  hidden: 100
  lag: 336
  horizon: 24
  revin: 1
  lookback_idx: 168

training:
  loss: mse
  bs: 200
  steps: 20000
  lr: 0.000001
  schedule: False
  print: True
  valid_steps: 100
  test_steps: 200
  n_prints: 10
  n_evals: 100

misc:
  seed:
  outputdir: outputs/
  smth: 1